# Generated by Django 4.2.25 on 2025-11-06 08:29

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importateur', models.CharField(max_length=255)),
                ('container', models.CharField(max_length=100)),
                ('marchandise', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fob', models.CharField(default=1, max_length=100)),
                ('cif', models.CharField(default=1, max_length=255)),
                ('num_bl', models.CharField(max_length=100)),
                ('num_fbr_aa', models.CharField(max_length=100)),
                ('plaque', models.CharField(max_length=50)),
                ('num_e', models.CharField(max_length=100)),
                ('origine', models.CharField(max_length=255)),
                ('provenance', models.CharField(max_length=255)),
                ('transitaire', models.CharField(max_length=255)),
                ('num_ref', models.CharField(default=1, max_length=100)),
                ('mois_ref', models.CharField(default=1, max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('frais_controle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_analyse_labo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nb_no', models.CharField(max_length=100)),
                ('bv_num', models.CharField(default=1, max_length=100)),
                ('recu_no', models.CharField(max_length=100)),
                ('liquidation_no', models.CharField(max_length=100)),
                ('travail_laboratoire', models.CharField(max_length=255)),
                ('destination', models.CharField(default=1, max_length=255)),
                ('num_av', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtatSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('importateur', models.CharField(blank=True, max_length=200)),
                ('container', models.CharField(blank=True, max_length=100)),
                ('marchandises', models.TextField(blank=True)),
                ('quantite', models.CharField(blank=True, max_length=100)),
                ('poids', models.CharField(blank=True, max_length=100)),
                ('fob', models.CharField(blank=True, max_length=100)),
                ('cif', models.CharField(blank=True, max_length=100)),
                ('num_bl', models.CharField(blank=True, max_length=100)),
                ('num_feriad', models.CharField(blank=True, max_length=100, verbose_name='Num. FERI/AD')),
                ('plaque', models.CharField(blank=True, max_length=100)),
                ('num_e', models.CharField(blank=True, max_length=100, verbose_name='Num. E')),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('provenance', models.CharField(blank=True, max_length=100)),
                ('transitaire', models.CharField(blank=True, max_length=200)),
                ('frais_controle', models.CharField(blank=True, max_length=100)),
                ('frais_analyse', models.CharField(blank=True, max_length=100)),
                ('tva', models.CharField(blank=True, max_length=100)),
                ('total_brut', models.CharField(blank=True, max_length=100)),
                ('nd_num', models.CharField(blank=True, max_length=100, verbose_name='N.D. n°')),
                ('recu_num', models.CharField(blank=True, max_length=100, verbose_name='Reçu n°')),
                ('bv_num', models.CharField(blank=True, max_length=100, verbose_name='B.V n°')),
                ('liquidation_num', models.CharField(blank=True, max_length=100, verbose_name='Liquidation n°')),
                ('produit_labo', models.CharField(blank=True, max_length=200, verbose_name='Produit/Laboratoire')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.ManyToManyField(related_name='desc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
