# Generated by Django 4.2.25 on 2025-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerne',
            name='num_av',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
